### ISSUE TITLE
正则表达式

### ISSUE THREAD

**Issue by ting-yu61** [Yexxxxx/-#1]
@Yexxxxx 
输入语句“如果 气温 大于 八 则 看看 “你好，世界” 否则 看看 “冻死我了””时出错
显示代码第17行有错误
re 模块无find()
re 模块：
![image](https://user-images.githubusercontent.com/60460063/74213474-4f927f00-4cd4-11ea-9945-a8b9663098a4.png)

**Comment by Yexxxxx** [comment]
已更新到第四版
