### ISSUE TITLE
小瑕疵

### ISSUE THREAD

**Issue by shu295** [Yexxxxx/-#5]
1.当输入小数时,没有进行报错处理
![7](https://user-images.githubusercontent.com/51659758/74243576-fac62700-4d1a-11ea-9544-4ee2d9b78c09.PNG)
2.如果能够再算除以时,加上除数不能为零的判断就更好了

**Comment by Yexxxxx** [comment]
已更新至第六版....
程序支持小数运算（可把我给整秃了）
除数为零报错
