### ISSUE TITLE
输出问题

### ISSUE THREAD

**Issue by crush-w** [Yexxxxx/-#7]
以下两种情况的输入，输出会出错
![image](https://user-images.githubusercontent.com/60460265/74535099-15dda480-4f70-11ea-96bb-86381cd02904.png)
![image](https://user-images.githubusercontent.com/60460265/74535327-8ab0de80-4f70-11ea-9a18-b926488c8c24.png)

**Comment by Yexxxxx** [comment]
那个，我的浏览器不知道为什么看不了github的图片，能不能麻烦你把bug步骤写出来

**Comment by Yexxxxx** [comment]
好啦好啦，都搞定了，(~ -.-)~
